<body>
  <div class="index">
    <h1 class="title">Books</h1>
    <table>
        <tr>
          <th>Title</th>
          <th>Body</th>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <% Book.all.each do |book|%>
          <tr>
            <td><%= book.title%></td>
            <td><%= book.body%></td>
            <td><%= link_to "show", book_path(book.id)%></td>
            <td><%= link_to "edit", edit_book_path(book.id)%></td>
            <td><%= link_to "destroy", book_path(book.id), method: :delete, "data-confirm"=>"Are you sure?" %></td>
          </tr>
        <% end %>
    </table>
  </div>

  <div class="create">
    <h2>New Book</h2>
    <% if @book.errors.any? %>
      <div>
        <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with model: @book, url: "/books", method: :post do |f|%>
    <!--model: @bookだとエラーが発生するが、model: Book.newだと発生しない…なぜ？？-->
      <label>Title</label>
      <%= f.text_field :title%>

      <label>Body</label>
      <%= f.text_area :body%>

      <%= f.submit "Create Book"%>
    <% end %>
  </div>

</body>